### PR TITLE
Jkintana hydrate about page

### PR DESCRIPTION
**Pull request by jkintana**
Apparently this got overridden -- this change reads rich text smartly instead of manually reading text, hyperlinks, etc. Left in getHtmlText in case others want to see/test.

### CODE REVIEW

**Review by JackBlake-zkq — CHANGES_REQUESTED** [review]
Doesn't look like we actually need Typescript here, could you change everything back to just Javascript? Using Typescript would definitely be the best practice (defining our content model with types), but I'd rather not introduce that complexity in the project since it's pretty small scale.

**Comment by JackBlake-zkq** [comment]
Also it does look like the Typescript file busts the website without explicitly setting it up, it still builds but any request made responds with 404.

**Review by JackBlake-zkq — CHANGES_REQUESTED** [review]
Looks like you need to do a merge from main. This version is still using the Cloudflare Adapter but we are using Netlify now.

**Comment by JackBlake-zkq** [comment]
We are using flowbite now, no need to remove that dependency. Add it back to the package.json and the tailwind config and it should all work

**Comment by jkintana** [comment]
Yeah just realized. Fixing now

**Review by JackBlake-zkq — APPROVED** [review]
Looks good 👍 It looks like you may have been right that we don't need the flowbite dependency though. We can merge this though and I'll look into that separately

**Pull request merged**
