### PR TITLE
created a navbar with flowbite

### LINKED ISSUE #14: Improve coloring and styling on navbar
Use [DSSD Global Website](https://dssdglobal.org/) for inspiration.

### LINKED ISSUE #15: Make navbar into its own component

### PR DESCRIPTION
**Pull request by sarthyparty**

### CODE REVIEW

**Comment by sarthyparty** [comment]
i used flowbite to create a responsive navbar, other than the colors i think its very similar to the navbar on the actual DSSD website

**Comment by sarthyparty** [comment]
also i was thinking the big blue button could be used to subscribe to an email list or something like that but we can get rid of it

**Review by JackBlake-zkq — CHANGES_REQUESTED** [review]
Love the clean look and colors. I think we can replicate this without flowbite without too much difficulty (want that clean dependency graph 😎). Also add the Navbar component into the Page Template so it shows up on each page. There have been some changes to main so be sure to pull before making changes 👍

**Comment by JackBlake-zkq** [comment]
Never mind I think Flowbite is worth it to simplify our frontend code. Just pull from main and add the Navbar to the Template and we should be good 👍

**Review by JackBlake-zkq — APPROVED** [review]
Looks Good!

**Pull request merged**
